= Examples for Polkadot Java Client

Code examples used in the link:../docs/[Documentation]

== Encoding

Examples for SCALE add SS58

.Run
----
cd encoding
./gradlew run
----

== Types

Examples for DotAmount, formatting, hashes and Address

.Run
----
cd types
./gradlew run
----

== RPC

Examples for accessing JSON RPC through HTTP or WebSockets.
The examples expect Polkadot node running and listening for RPC and WS requests on the localhost (i.e. default node options). In any of the following examples you can pass the optional `--args="okhttp"` to the run command to use the Java 8 compatible OkHttp implementation of the RPC and WebSocket adapters.

.Show current head
----
cd rpc
./gradlew run --args="okhttp"
----

.Follow updates to the current head (use `Ctrl+C` to exit)
----
cd rpc
./gradlew run -PmainClass=FollowState --args="okhttp"
----

.Describe runtime
----
cd rpc
./gradlew run -PmainClass=DescribeRuntime
----

NOTE: Currently, only runtimes with Metadata are is supported https://github.com/paritytech/polkadot/releases/tag/v0.8.30[v0.8.30] is suitable version to test with.


== Runtime Explorer

A web-based explorer of the Runtime Metadata.
The examples expect Polkadot node running and listening for RPC requests on the localhost (i.e. default node options)

----
cd runtime-explorer
./gradlew bootRun
----

Open http://localhost:8080

== Keys

Generate Secret/Public Keys and Address

----
cd keys
./gradlew run
----

== Balance check and transfer

Check account status and/or make a transfer of the balance to another address.

.For the development network, transfer random amount for Alice to Bob
----
cd balance
./gradlew run
----

NOTE: To run a development network use: `polkadot --dev`

NOTE: Currently, only runtimes with Metadata are is supported https://github.com/paritytech/polkadot/releases/tag/v0.8.30[v0.8.30] is suitable version to test with.


.Transfer using real network (ex. Kusama)
----
cd balance
./gradlew run --args="wss://cc3-5.kusama.network SENDER_KEY_SEED RECIPIENT_ADDRESS"
----

WARNING: If you use on a real network please be aware that it executes the transfer without any additional confirmation from you