= Standard RPC Commands and Subscriptions

== RPC Commands
:shortcut-base: StandardCommands.getInstance()

* Chain
- <<getBlock>>
- <<getFinalizedHead>>
* System
- <<systemChain>>
- <<systemHealth>>
- <<systemName>>
* Other
- <<methods>>

[#getBlock]
=== Get Block (`chain_getBlock`)

Get block by its hash

Shortcut:: `{shortcut-base}.getBlock(Hash256)`
Command:: `chain_getBlock`
Parameters:: hash of the requested block
Java Object:: `BlockResponseJson`

.BlockResponseJson Properties
- `BlockJson getBlock()` block details
- `Object getJustification()`

[#getFinalizedHead]
=== Get Finalised Head (`chain_getFinalizedHead`)

Get the hash of the finalized head

Shortcut:: `{shortcut-base}.getFinalizedHead()`
Command:: `chain_getFinalizedHead`
Parameters:: none
Java Object:: `Hash256`

[#systemChain]
=== System Chain (`system_chain`)

Get name of the current blockchain

Shortcut:: `{shortcut-base}.systemChain()`
Command:: `system_chain`
Parameters:: none
Java Object:: `String`

[#systemHealth]
=== System Health (`system_health`)

Get health status of the node

Shortcut:: `{shortcut-base}.systemHealth()`
Command:: `system_health`
Parameters:: none
Java Object:: `SystemHealthJson`

.SystemHealthJson Properties
- `Boolean getSyncing` - true if node does initial syncing
- `Integer getPeers()` - amount of current peers
- `Boolean getShouldHavePeers()` - true if node should have peers

[#systemName]
=== System Name (`system_name`)

Get name of the current node

Shortcut:: `{shortcut-base}.systemName()`
Command:: `system_name`
Parameters:: none
Java Object:: `String`

[#methods]
=== Methods List (`rpc_methods`)

Get list of all available RPC methods

Shortcut:: `{shortcut-base}.methods()`
Command:: `rpc_methods`
Parameters:: none
Java Object:: `MethodsJson`

.MethodsJson Properties
- `Integer getVersion()` - version of RPC
- `List<String> getMethods()` - list of methods

== Subscriptions
:shortcut-base: StandardSubscriptions.getInstance()

- <<newHeads>>

[#newHeads]
=== New Heads (`chain_subscribeNewHead`)

Subscribe to the head changes, i.e. to block on the head of the current blockchain.

Shortcut:: `{shortcut-base}.newHeads()`
Command:: `chain_subscribeNewHead`
Parameters:: none
Java Object:: `BlockJson.Header`
